apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  namespace: couchbase
  name: promotion
  labels:
    cluster: couchbase-cluster
  annotations:
    cluster: couchbase-cluster
spec:
  compressionMode: active
  conflictResolution: seqno
  enableFlush: false
  enableIndexReplica: false
  evictionPolicy: valueOnly
  ioPriority: high
  maxTTL: '0'
  memoryQuota: 100Mi
  minimumDurability: none # none, majority, majorityAndPersistActive, persistToMajority
  name: promotion
  replicas: 1
  scopes:
    managed: false
    resources:
    - kind: CouchbaseScope
      name: ""
    selector: {}





